name: Ruby

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - run: bundle install
    - name: Rubocop
      run: bundle exec rubocop -F **/*.rb
